CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --standalone --nnodes 1 --nproc-per-node 4 vla-scripts/finetune.py \
  --vla_path /data1/Models/openvla-7b \
  --data_root_dir /data3/embodied/modified_libero_rlds \
  --dataset_name libero_4_task_suites_no_noops \
  --run_root_dir /data3/zrs/models/cogvla-libero-4task \
  --use_l1_regression True \
  --use_diffusion False \
  --use_film True \
  --use_aggr True \
  --num_vision_aggr 64 \
  --use_lfp True \
  --lfp_average_factor 0.5 \
  --lfp_type 'shiftedcos_decay_0.85_0.15' \
  --lfp_enable_film True \
  --num_images_in_input 2 \
  --use_proprio True \
  --batch_size 16 \
  --grad_accumulation_steps 1 \
  --learning_rate 5e-4 \
  --max_steps 80005 \
  --save_freq 10000 \
  --merge_lora_during_training False \
  --save_latest_checkpoint_only False \
  --image_aug True \
  --lora_rank 32 \
  --wandb_entity "ENTITY" \
  --wandb_project "PROJECT" \
  --run_id_note cogvla-libero-4task