CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --standalone --nnodes 1 --nproc-per-node 8 vla-scripts/finetune.py \
  --vla_path /data1/Models/openvla-7b \
  --data_root_dir /data1/ALOHA/tensorflow_datasets \
  --dataset_name aloha_open_the_drawer_place_the_toy_in_the_drawer_and_then_close_it_dataset \
  --run_root_dir /data/models/cogvla-aloha/open_the_drawer \
  --use_l1_regression True \
  --use_diffusion False \
  --use_film True \
  --use_aggr True \
  --num_vision_aggr 64 \
  --use_lfp True \
  --lfp_average_factor 0.5 \
  --lfp_type 'shiftedcos_decay_0.85_0.15' \
  --lfp_enable_film True \
  --num_images_in_input 3 \
  --use_proprio True \
  --batch_size 4 \
  --grad_accumulation_steps 1 \
  --learning_rate 5e-4 \
  --max_steps 80005 \
  --save_freq 10000 \
  --merge_lora_during_training False \
  --save_latest_checkpoint_only False \
  --image_aug True \
  --lora_rank 32 \
  --wandb_entity "ENTITY" \
  --wandb_project "PROJECT" \
  --run_id_note run_id